export enum RouteType {
  START = 'START',
  VISIT = 'VISIT',
  FINISH_AT_DEPOT = 'FINISH_AT_DEPOT',
  FINISH_AT_HOTEL = 'FINISH_AT_HOTEL',
  START_FROM_DEPOT = 'START_FROM_DEPOT',
  START_FROM_HOTEL = 'START_FROM_HOTEL',
  FINISH = 'FINISH',
  START_SEGMENT = 'START_SEGMENT',
  FINISH_SEGMENT = 'FINISH_SEGMENT'
}
